# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# - task: SonarCloudPrepare@1
#   inputs:
#         SonarCloud: 'SonarCloudConnection1'
#         organization: 'qiagenda'
#         scannerMode: 'MSBuild'
#         projectKey: 'QiagenDA_OPCUA'
#         projectName: 'OPCUA'
#         extraProperties: |
#           sonar.javascript.node.maxspace=4096
#           sonar.exclusions=**/d3.js,**/lib/DataTables/**,**/views_backup*.sql
#           sonar.log.level=DEBUG- task: NuGetToolInstaller@1

# NuGet tool installer
- task: NuGetToolInstaller@1

# NuGet
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Visual Studio MSBuild
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
